"""
Export Components for QBR Auto-Drafter

Provides functionality to export QBR documents to:
- Markdown (.md) files
- PDF documents with Monday.com branding
- JSON structured data
"""

import io
import re
from datetime import datetime
from typing import Dict, Any, Optional
from fpdf import FPDF


# Monday.com brand colors (RGB)
MONDAY_COLORS = {
    'primary': (97, 97, 255),      # #6161FF
    'primary_dark': (75, 75, 204), # #4B4BCC
    'success': (0, 202, 114),      # #00CA72
    'warning': (253, 171, 61),     # #FDAB3D
    'danger': (226, 68, 92),       # #E2445C
    'text_primary': (50, 51, 56),  # #323338
    'text_secondary': (103, 104, 121),  # #676879
    'bg': (246, 247, 251),         # #F6F7FB
    'white': (255, 255, 255)
}


def export_to_markdown(
    qbr_content: str,
    account_name: str,
    client_data: Optional[Dict[str, Any]] = None
) -> str:
    """
    Export QBR to a formatted Markdown document.
    
    Args:
        qbr_content: The raw QBR content in markdown format
        account_name: Name of the account
        client_data: Optional client data for metadata
        
    Returns:
        Complete markdown document as string
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    quarter = "Q3 2025"  # Could be dynamic
    
    # Build metadata header
    header = f"""---
title: Quarterly Business Review - {account_name}
quarter: {quarter}
generated: {timestamp}
generator: monday.com QBR Auto-Drafter
---

# 📊 Quarterly Business Review
## {account_name} | {quarter}

*Generated on {timestamp} by AI-powered QBR Auto-Drafter*

---

"""
    
    # Add metrics summary if client data provided
    metrics_section = ""
    if client_data:
        plan = client_data.get('plan_type', 'N/A')
        users = client_data.get('active_users', 0)
        risk = client_data.get('risk_engine_score', 0)
        nps = client_data.get('nps_score', 0)
        
        risk_label = "🟢 Low" if risk < 0.3 else "🟡 Medium" if risk < 0.6 else "🔴 High"
        
        metrics_section = f"""
## 📈 Key Metrics at a Glance

| Metric | Value |
|--------|-------|
| Plan Type | {plan} |
| Active Users | {users:,} |
| Risk Level | {risk_label} ({risk:.0%}) |
| NPS Score | {nps}/10 |

---

"""
    
    # Footer
    footer = """

---

*This QBR was generated using monday.com's AI-powered QBR Auto-Drafter prototype.*
*Built for the Innovation Builder Assessment | December 2024*
"""
    
    return header + metrics_section + qbr_content + footer


def get_markdown_download_data(
    qbr_content: str,
    account_name: str,
    client_data: Optional[Dict[str, Any]] = None
) -> tuple:
    """
    Get markdown content and filename for download.
    
    Returns:
        Tuple of (content_bytes, filename)
    """
    content = export_to_markdown(qbr_content, account_name, client_data)
    safe_name = re.sub(r'[^\w\s-]', '', account_name).strip().replace(' ', '_')
    filename = f"QBR_{safe_name}_Q3_2025.md"
    
    return content.encode('utf-8'), filename


class MondayPDF(FPDF):
    """
    Custom PDF class with Monday.com branding.
    """
    
    def __init__(self, account_name: str = ""):
        super().__init__()
        self.account_name = account_name
        self.set_auto_page_break(auto=True, margin=25)
    
    def header(self):
        """Render page header with Monday branding."""
        # Header background
        self.set_fill_color(*MONDAY_COLORS['primary'])
        self.rect(0, 0, 210, 25, 'F')
        
        # Logo placeholder (text-based)
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(*MONDAY_COLORS['white'])
        self.set_xy(10, 8)
        self.cell(0, 10, 'monday.com', ln=False)
        
        # QBR title
        self.set_font('Helvetica', '', 10)
        self.set_xy(150, 8)
        self.cell(0, 10, 'Quarterly Business Review', ln=True)
        
        # Reset position
        self.set_xy(10, 35)
    
    def footer(self):
        """Render page footer."""
        self.set_y(-20)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(*MONDAY_COLORS['text_secondary'])
        
        # Page number
        self.cell(0, 10, f'Page {self.page_no()}', align='C')
        
        # Generated info
        self.set_y(-15)
        self.cell(0, 10, f'Generated by QBR Auto-Drafter | {datetime.now().strftime("%Y-%m-%d")}', align='C')
    
    def add_title_page(self, account_name: str, quarter: str = "Q3 2025"):
        """Add a branded title page."""
        self.add_page()
        
        # Large gradient-like header
        self.set_fill_color(*MONDAY_COLORS['primary'])
        self.rect(0, 0, 210, 100, 'F')
        
        # Decorative accent
        self.set_fill_color(*MONDAY_COLORS['primary_dark'])
        self.rect(0, 95, 210, 10, 'F')
        
        # Title
        self.set_font('Helvetica', 'B', 28)
        self.set_text_color(*MONDAY_COLORS['white'])
        self.set_xy(0, 30)
        self.cell(0, 15, 'Quarterly Business Review', align='C', ln=True)
        
        # Account name
        self.set_font('Helvetica', '', 18)
        self.set_xy(0, 50)
        self.cell(0, 10, account_name, align='C', ln=True)
        
        # Quarter
        self.set_font('Helvetica', 'B', 14)
        self.set_xy(0, 70)
        self.cell(0, 10, quarter, align='C', ln=True)
        
        # Subtitle below header
        self.set_text_color(*MONDAY_COLORS['text_primary'])
        self.set_font('Helvetica', 'I', 11)
        self.set_xy(0, 120)
        self.cell(0, 10, 'AI-Generated Strategic Account Review', align='C', ln=True)
        
        # Generation date
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*MONDAY_COLORS['text_secondary'])
        self.set_xy(0, 135)
        self.cell(0, 10, f'Generated: {datetime.now().strftime("%B %d, %Y")}', align='C')
    
    def add_section_header(self, title: str, icon: str = ""):
        """Add a styled section header."""
        self.ln(8)
        
        # Section header background
        self.set_fill_color(*MONDAY_COLORS['bg'])
        self.set_draw_color(*MONDAY_COLORS['primary'])
        
        # Left accent bar
        current_y = self.get_y()
        self.set_fill_color(*MONDAY_COLORS['primary'])
        self.rect(10, current_y, 3, 10, 'F')
        
        # Title text
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(*MONDAY_COLORS['text_primary'])
        self.set_x(18)
        self.cell(0, 10, f'{icon} {title}' if icon else title, ln=True)
        
        self.ln(3)
    
    def add_metric_box(self, label: str, value: str, color: str = 'primary'):
        """Add a styled metric box."""
        color_rgb = MONDAY_COLORS.get(color, MONDAY_COLORS['primary'])
        
        # Box background
        current_x = self.get_x()
        current_y = self.get_y()
        
        self.set_fill_color(245, 246, 250)
        self.rect(current_x, current_y, 55, 25, 'F')
        
        # Left accent
        self.set_fill_color(*color_rgb)
        self.rect(current_x, current_y, 3, 25, 'F')
        
        # Value
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(*color_rgb)
        self.set_xy(current_x + 8, current_y + 3)
        self.cell(45, 8, str(value), ln=True)
        
        # Label
        self.set_font('Helvetica', '', 8)
        self.set_text_color(*MONDAY_COLORS['text_secondary'])
        self.set_xy(current_x + 8, current_y + 13)
        self.cell(45, 6, label)
        
        self.set_xy(current_x + 60, current_y)
    
    def add_paragraph(self, text: str):
        """Add a paragraph of text."""
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*MONDAY_COLORS['text_primary'])
        self.multi_cell(0, 6, text)
        self.ln(3)
    
    def add_bullet_point(self, text: str, level: int = 0):
        """Add a bullet point."""
        indent = 15 + (level * 10)
        self.set_x(indent)
        
        # Bullet
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*MONDAY_COLORS['primary'])
        self.cell(5, 6, chr(149))  # Bullet character
        
        # Text
        self.set_text_color(*MONDAY_COLORS['text_primary'])
        self.multi_cell(0, 6, text)
    
    def add_risk_badge(self, risk_score: float):
        """Add a risk level badge."""
        if risk_score >= 0.6:
            color = MONDAY_COLORS['danger']
            label = "HIGH RISK"
        elif risk_score >= 0.3:
            color = MONDAY_COLORS['warning']
            label = "MEDIUM RISK"
        else:
            color = MONDAY_COLORS['success']
            label = "LOW RISK"
        
        current_x = self.get_x()
        current_y = self.get_y()
        
        # Badge background
        self.set_fill_color(*color)
        self.rect(current_x, current_y, 40, 8, 'F')
        
        # Badge text
        self.set_font('Helvetica', 'B', 8)
        self.set_text_color(*MONDAY_COLORS['white'])
        self.set_xy(current_x + 2, current_y + 1)
        self.cell(36, 6, label, align='C')
        
        self.set_xy(current_x + 45, current_y)


def parse_markdown_to_sections(markdown: str) -> Dict[str, str]:
    """
    Parse markdown content into sections.
    
    Args:
        markdown: Raw markdown content
        
    Returns:
        Dictionary of section title -> content
    """
    sections = {}
    current_section = "Introduction"
    current_content = []
    
    for line in markdown.split('\n'):
        # Check for headers
        if line.startswith('## ') or line.startswith('### '):
            # Save previous section
            if current_content:
                sections[current_section] = '\n'.join(current_content).strip()
            
            # Start new section
            current_section = line.lstrip('#').strip()
            current_content = []
        else:
            current_content.append(line)
    
    # Save last section
    if current_content:
        sections[current_section] = '\n'.join(current_content).strip()
    
    return sections


def clean_text_for_pdf(text: str) -> str:
    """Clean markdown syntax for PDF rendering."""
    # Remove markdown formatting
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)  # Bold
    text = re.sub(r'\*(.+?)\*', r'\1', text)       # Italic
    text = re.sub(r'`(.+?)`', r'\1', text)         # Code
    text = re.sub(r'\[(.+?)\]\(.+?\)', r'\1', text)  # Links
    
    # Remove emojis (basic ASCII replacement)
    emoji_pattern = re.compile("["
        u"\U0001F600-\U0001F64F"
        u"\U0001F300-\U0001F5FF"
        u"\U0001F680-\U0001F6FF"
        u"\U0001F1E0-\U0001F1FF"
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        "]+", flags=re.UNICODE)
    text = emoji_pattern.sub('', text)
    
    return text.strip()


def export_to_pdf(
    qbr_content: str,
    account_name: str,
    client_data: Dict[str, Any]
) -> bytes:
    """
    Export QBR to a branded PDF document.
    
    Args:
        qbr_content: The raw QBR content in markdown format
        account_name: Name of the account
        client_data: Client data for metrics
        
    Returns:
        PDF document as bytes
    """
    pdf = MondayPDF(account_name)
    
    # Title page
    pdf.add_title_page(account_name)
    
    # Metrics overview page
    pdf.add_page()
    pdf.add_section_header("Key Metrics Overview", "")
    pdf.ln(5)
    
    # Metrics row
    start_x = 15
    pdf.set_xy(start_x, pdf.get_y())
    
    # Risk score
    risk = client_data.get('risk_engine_score', 0)
    risk_color = 'danger' if risk >= 0.6 else 'warning' if risk >= 0.3 else 'success'
    pdf.add_metric_box("Churn Risk", f"{risk:.0%}", risk_color)
    
    # NPS
    nps = client_data.get('nps_score', 0)
    nps_color = 'success' if nps >= 8 else 'danger' if nps < 6 else 'warning'
    pdf.add_metric_box("NPS Score", f"{nps}/10", nps_color)
    
    # Active Users
    users = client_data.get('active_users', 0)
    pdf.add_metric_box("Active Users", f"{users:,}", 'primary')
    
    pdf.ln(30)
    
    # Second metrics row
    pdf.set_xy(start_x, pdf.get_y())
    
    # Growth
    growth = client_data.get('usage_growth_qoq', 0)
    if isinstance(growth, float) and abs(growth) <= 1:
        growth = growth * 100
    growth_color = 'success' if growth > 0 else 'danger'
    pdf.add_metric_box("QoQ Growth", f"{growth:+.0f}%", growth_color)
    
    # Automation
    automation = client_data.get('automation_adoption_pct', 0)
    if isinstance(automation, float) and automation <= 1:
        automation = automation * 100
    auto_color = 'success' if automation >= 60 else 'warning' if automation >= 30 else 'danger'
    pdf.add_metric_box("Automation", f"{automation:.0f}%", auto_color)
    
    # Health Score
    scat = client_data.get('scat_score', 0)
    scat_color = 'success' if scat >= 80 else 'warning' if scat >= 60 else 'danger'
    pdf.add_metric_box("Health (SCAT)", f"{scat}", scat_color)
    
    pdf.ln(35)
    
    # Parse and render QBR content
    sections = parse_markdown_to_sections(qbr_content)
    
    for section_title, content in sections.items():
        if not content.strip():
            continue
        
        # Check if we need a new page
        if pdf.get_y() > 240:
            pdf.add_page()
        
        # Clean section title
        clean_title = clean_text_for_pdf(section_title)
        if clean_title:
            pdf.add_section_header(clean_title)
        
        # Process content
        lines = content.split('\n')
        for line in lines:
            clean_line = clean_text_for_pdf(line)
            if not clean_line:
                continue
            
            # Check for bullet points
            if line.strip().startswith('- ') or line.strip().startswith('* '):
                bullet_text = clean_line.lstrip('- *').strip()
                pdf.add_bullet_point(bullet_text)
            elif line.strip().startswith(('1.', '2.', '3.')):
                # Numbered list
                pdf.add_bullet_point(clean_line)
            else:
                pdf.add_paragraph(clean_line)
        
        pdf.ln(5)
    
    # CRM Notes section
    if pdf.get_y() > 220:
        pdf.add_page()
    
    pdf.add_section_header("Account Notes")
    crm_notes = client_data.get('crm_notes', 'No notes available.')
    pdf.add_paragraph(clean_text_for_pdf(crm_notes))
    
    pdf.ln(5)
    pdf.add_section_header("Customer Feedback")
    feedback = client_data.get('feedback_summary', 'No feedback recorded.')
    pdf.add_paragraph(clean_text_for_pdf(feedback))
    
    # Return as bytes
    return bytes(pdf.output())


def get_pdf_download_data(
    qbr_content: str,
    account_name: str,
    client_data: Dict[str, Any]
) -> tuple:
    """
    Get PDF content and filename for download.
    
    Returns:
        Tuple of (content_bytes, filename)
    """
    pdf_bytes = export_to_pdf(qbr_content, account_name, client_data)
    safe_name = re.sub(r'[^\w\s-]', '', account_name).strip().replace(' ', '_')
    filename = f"QBR_{safe_name}_Q3_2025.pdf"
    
    return pdf_bytes, filename


def export_batch_to_markdown(
    qbr_results: Dict[str, str],
    all_client_data: Dict[str, Dict[str, Any]]
) -> str:
    """
    Export multiple QBRs to a single markdown document.
    
    Args:
        qbr_results: Dictionary of account_name -> qbr_content
        all_client_data: Dictionary of account_name -> client_data
        
    Returns:
        Combined markdown document
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    document = f"""---
title: Quarterly Business Review - Portfolio Summary
quarter: Q3 2025
accounts: {len(qbr_results)}
generated: {timestamp}
---

# 📊 Portfolio Quarterly Business Review
## Q3 2025 | All Accounts Summary

*Generated on {timestamp}*

---

## Portfolio Overview

| Account | Plan | Risk Level | NPS | Growth |
|---------|------|------------|-----|--------|
"""
    
    # Add summary table
    for account_name, client_data in all_client_data.items():
        risk = client_data.get('risk_engine_score', 0)
        risk_emoji = "🟢" if risk < 0.3 else "🟡" if risk < 0.6 else "🔴"
        nps = client_data.get('nps_score', 0)
        growth = client_data.get('usage_growth_qoq', 0)
        if isinstance(growth, float) and abs(growth) <= 1:
            growth = growth * 100
        plan = client_data.get('plan_type', 'N/A')
        
        document += f"| {account_name} | {plan} | {risk_emoji} {risk:.0%} | {nps}/10 | {growth:+.0f}% |\n"
    
    document += "\n---\n\n"
    
    # Add individual QBRs
    for account_name, qbr_content in qbr_results.items():
        document += f"\n# {account_name}\n\n"
        document += qbr_content
        document += "\n\n---\n"
    
    return document

